<?php

	// IMPORTANT:
	// ==========
	// When translating, only translate the strings that are
	// TO THE RIGHT OF the arrow sign (=>).
	//
	// Do NOT translate the strings between square brackets ([]) or (<>)
	// =====================================================
	$ReportTranslation = array(
		'back' => "Back",
		'print report' => "Print Report",
		'export report to csv file' => "Export report to CSV file",
		'records' => "<n> records",
		'from to' => "from <FROM> to <TO>",
		'period from to' => "Period from <FROM> to <TO>",
		'change' => "Change",
		'report configuration' => "Report Configuration",
		'report period' => "Report Period",
		'month to date' => "Month-to-date",
		'month to date description' => 'Include data from month-to-date. Compare with the same period last month, and the same period last year.',
		'current month' => "Current month",
		'current month description' => 'Include data from the entire current month. Compare with last month, and the same month last year.',
		'last month' => "Last month",
		'last month description' => 'Include data from last month. Compare with the month before, and the same month last year.',
		'quarter to date' => "Quarter-to-date",
		'quarter to date description' => 'Include data from quarter-to-date. Compare with the same period last quarter, and the same period last year.',
		'current quarter' => "Current quarter",
		'current quarter description' => 'Include data from current quarter. Compare with the last one and the same quarter last year.',
		'last quarter' => "Last quarter",
		'last quarter description' => 'Include data from last quarter. Compare with the quarter before and the same quarter last year.',
		'year to date' => "Year-to-date",
		'year to date description' => 'Include data from year-to-date. Compare with same period last year and the same period the year before.',
		'current year' => "Current year",
		'current year description' => 'Include data from current year. Compare with last year and the year before.',
		'last year' => "Last year",
		'last year description' => 'Include data from last year. Compare to the two years before.',
		'comparison period 1' => "Comparison Period 1",
		'comparison period 2' => "Comparison Period 2",
		'from' => "From",
		'to' => "To",
		'order by' => "Order by",
		'descending' => "Descending",
		'ascending' => "Ascending",
		'appearance' => "Appearance (applies instantly)",
		'show row numbers' => "Show row numbers",
		'alignment of label column' => "Alignment of <LABEL> column",
		'alignment of other columns' => "Alignment of other columns",
		'apply' => "Apply",
		'close' => "Close",
		'charts-color-theme' => 'Charts color theme',
		'rainbow' => 'Rainbow',
		'reds' => 'Red shades',
		'oranges' => 'Orange shades',
		'yellows' => 'Yellow shades',
		'greens' => 'Green shades',
		'blues' => 'Blue shades',
		'violets' => 'Violet shades',
		'grays' => 'Gray shades',
		'barchart-orientation' => 'Bar chart orientation',
		'barchart-aspect-ratio' => 'Bar chart aspect ratio (height : width)',
		'barchart-bar-width' => 'Bars width in the bar chart (pixels)',
		'barchart-bar-spacing' => 'Bars spacing in the bar chart (pixels)',
		'barchart-bar-width-default-hint' => 'A value of 0 (the default) sets the bar width automatically.',
		'barchart-width' => 'Width of bar chart',
		'piechart-width' => 'Width of pie charts',
		'piechart-labels' => 'Labels on pie charts',
		'labels' => 'Labels',
		'labels-values' => 'Labels and values',
		'labels-percentages' => 'Labels and percentages',
		'labels-values-percentages' => 'Labels, values and percentages',
		'automatic' => 'Automatic',
		'loading report header' => 'Loading report header ...',
		'loading report footer' => 'Loading report footer ...',
		'no-report-data' => 'Either no data was found for this report, or you don\'t have sufficient permissions.',
	);